// The RTMP server bundled with the app: go2rtc (github.com/AlexxIT/go2rtc, MIT, ~20 MB), chosen for
// its size. It takes the camera's RTMP push into a declared stream and serves it over RTSP.
#pragma once

#include <utility>

#include "rtmp_server.h"

class Go2RtcServer : public RtmpServer {
public:
    Go2RtcServer(QString program, QObject* parent) : RtmpServer(std::move(program), parent) {}

    QString name() const override { return QStringLiteral("go2rtc"); }
    QString ingestUrl(const QString& host) const override {
        return QStringLiteral("rtmp://%1:%2/%3").arg(host).arg(kRtmpPort).arg(streamName());
    }
    QString playbackUrl() const override { return QStringLiteral("rtsp://127.0.0.1:%1/%2").arg(kRtspPort).arg(streamName()); }
    QStringList shareUrls() const override { return {playbackUrl(), ingestUrl(QStringLiteral("127.0.0.1"))}; }

protected:
    QByteArray configuration() const override {
        // WebRTC and SRTP off; only RTMP listens on the network.
        return QStringLiteral("# Generated by DJI VCam at every start.\n"
                              "api:\n  listen: \"127.0.0.1:%1\"\n"
                              "rtsp:\n  listen: \"127.0.0.1:%2\"\n"
                              "rtmp:\n  listen: \":%3\"\n"
                              "webrtc:\n  listen: \"\"\n"
                              "srtp:\n  listen: \"\"\n"
                              "streams:\n  %4:\n")
            .arg(kApiPort)
            .arg(kRtspPort)
            .arg(kRtmpPort)
            .arg(streamName())
            .toUtf8();
    }
    QString configFileName() const override { return QStringLiteral("go2rtc.yaml"); }
    QStringList arguments(const QString& config_path) const override { return {QStringLiteral("-config"), config_path}; }
    QUrl statusUrl() const override { return QUrl(QStringLiteral("http://127.0.0.1:%1/api/streams").arg(kApiPort)); }
    QString parsePublisher(const QByteArray& reply) const override;

private:
    static constexpr quint16 kApiPort = 1984;
};
